#define __CUDA_API_VERSION_INTERNAL
#include "cuda.h"

#include "dllapi_p.h"
#include "dllapi.h"

using namespace DllAPI;
//namespace dllapi {
//namespace cuda {

DEFINE_DLL_INSTANCE_N("cuda", "nvcuda", NULL)

DEFINE_DLLAPI_ARG(1, CUresult, cuInit, unsigned int)
DEFINE_DLLAPI_ARG(1, CUresult, cuDriverGetVersion, int *)
DEFINE_DLLAPI_ARG(2, CUresult, cuDeviceGet, CUdevice *, int)
DEFINE_DLLAPI_ARG(1, CUresult, cuDeviceGetCount, int *)
DEFINE_DLLAPI_ARG(3, CUresult, cuDeviceGetName, char *, int, CUdevice)
DEFINE_DLLAPI_ARG(3, CUresult, cuDeviceComputeCapability, int *, int *, CUdevice)
DEFINE_DLLAPI_ARG(2, CUresult, cuDeviceTotalMem, int *, CUdevice)
DEFINE_DLLAPI_ARG(2, CUresult, cuDeviceTotalMem_v2, int *, CUdevice)
DEFINE_DLLAPI_ARG(2, CUresult, cuDeviceGetProperties, CUdevprop *, CUdevice)
DEFINE_DLLAPI_ARG(3, CUresult, cuDeviceGetAttribute, int *, CUdevice_attribute, CUdevice)
DEFINE_DLLAPI_ARG(3, CUresult, cuCtxCreate, CUcontext *, unsigned int, CUdevice)
DEFINE_DLLAPI_ARG(3, CUresult, cuCtxCreate_v2, CUcontext *, unsigned int, CUdevice)
DEFINE_DLLAPI_ARG(1, CUresult, cuCtxDestroy, CUcontext)
DEFINE_DLLAPI_ARG(1, CUresult, cuCtxDestroy_v2, CUcontext)
DEFINE_DLLAPI_ARG(2, CUresult, cuCtxAttach, CUcontext *, unsigned int)
DEFINE_DLLAPI_ARG(1, CUresult, cuCtxDetach, CUcontext)
DEFINE_DLLAPI_ARG(1, CUresult, cuCtxPushCurrent, CUcontext)
DEFINE_DLLAPI_ARG(1, CUresult, cuCtxPushCurrent_v2, CUcontext)
DEFINE_DLLAPI_ARG(1, CUresult, cuCtxPopCurrent, CUcontext *)
DEFINE_DLLAPI_ARG(1, CUresult, cuCtxPopCurrent_v2, CUcontext *)
DEFINE_DLLAPI_ARG(1, CUresult, cuCtxSetCurrent, CUcontext)
DEFINE_DLLAPI_ARG(1, CUresult, cuCtxGetCurrent, CUcontext *)
DEFINE_DLLAPI_ARG(1, CUresult, cuCtxGetDevice, CUdevice *)
DEFINE_DLLAPI_ARG(0, CUresult, cuCtxSynchronize)
DEFINE_DLLAPI_ARG(2, CUresult, cuCtxSetLimit, CUlimit, int)
DEFINE_DLLAPI_ARG(2, CUresult, cuCtxGetLimit, int *, CUlimit)
DEFINE_DLLAPI_ARG(1, CUresult, cuCtxGetCacheConfig, CUfunc_cache *)
DEFINE_DLLAPI_ARG(1, CUresult, cuCtxSetCacheConfig, CUfunc_cache)
DEFINE_DLLAPI_ARG(1, CUresult, cuCtxGetSharedMemConfig, CUsharedconfig *)
DEFINE_DLLAPI_ARG(1, CUresult, cuCtxSetSharedMemConfig, CUsharedconfig)
DEFINE_DLLAPI_ARG(2, CUresult, cuCtxGetApiVersion, CUcontext, unsigned int *)
DEFINE_DLLAPI_ARG(2, CUresult, cuModuleLoad, CUmodule *, const char *)
DEFINE_DLLAPI_ARG(2, CUresult, cuModuleLoadData, CUmodule *, const void *)
DEFINE_DLLAPI_ARG(5, CUresult, cuModuleLoadDataEx, CUmodule *, const void *, unsigned int, CUjit_option *, void **)
DEFINE_DLLAPI_ARG(2, CUresult, cuModuleLoadFatBinary, CUmodule *, const void *)
DEFINE_DLLAPI_ARG(1, CUresult, cuModuleUnload, CUmodule)
DEFINE_DLLAPI_ARG(3, CUresult, cuModuleGetFunction, CUfunction *, CUmodule, const char *)
DEFINE_DLLAPI_ARG(4, CUresult, cuModuleGetGlobal, CUdeviceptr *, int *, CUmodule, const char *)
DEFINE_DLLAPI_ARG(4, CUresult, cuModuleGetGlobal_v2, CUdeviceptr *, int *, CUmodule, const char *)
DEFINE_DLLAPI_ARG(3, CUresult, cuModuleGetTexRef, CUtexref *, CUmodule, const char *)
DEFINE_DLLAPI_ARG(3, CUresult, cuModuleGetSurfRef, CUsurfref *, CUmodule, const char *)
DEFINE_DLLAPI_ARG(2, CUresult, cuMemGetInfo, int *, int *)
DEFINE_DLLAPI_ARG(2, CUresult, cuMemGetInfo_v2, int *, int *)
DEFINE_DLLAPI_ARG(2, CUresult, cuMemAlloc, CUdeviceptr *, int)
DEFINE_DLLAPI_ARG(2, CUresult, cuMemAlloc_v2, CUdeviceptr *, int)
DEFINE_DLLAPI_ARG(5, CUresult, cuMemAllocPitch, CUdeviceptr *, int *, int, int, unsigned int)
DEFINE_DLLAPI_ARG(5, CUresult, cuMemAllocPitch_v2, CUdeviceptr *, int *, int, int, unsigned int)
DEFINE_DLLAPI_ARG(1, CUresult, cuMemFree, CUdeviceptr)
DEFINE_DLLAPI_ARG(1, CUresult, cuMemFree_v2, CUdeviceptr)
DEFINE_DLLAPI_ARG(3, CUresult, cuMemGetAddressRange, CUdeviceptr *, int *, CUdeviceptr)
DEFINE_DLLAPI_ARG(3, CUresult, cuMemGetAddressRange_v2, CUdeviceptr *, int *, CUdeviceptr)
DEFINE_DLLAPI_ARG(2, CUresult, cuMemAllocHost, void **, size_t)
DEFINE_DLLAPI_ARG(2, CUresult, cuMemAllocHost_v2, void **, size_t)
DEFINE_DLLAPI_ARG(1, CUresult, cuMemFreeHost, void *)
DEFINE_DLLAPI_ARG(3, CUresult, cuMemHostAlloc, void **, int, unsigned int)
DEFINE_DLLAPI_ARG(3, CUresult, cuMemHostGetDevicePointer, CUdeviceptr *, void *, unsigned int)
DEFINE_DLLAPI_ARG(3, CUresult, cuMemHostGetDevicePointer_v2, CUdeviceptr *, void *, unsigned int)
DEFINE_DLLAPI_ARG(2, CUresult, cuMemHostGetFlags, unsigned int *, void *)
DEFINE_DLLAPI_ARG(2, CUresult, cuDeviceGetByPCIBusId, CUdevice *, char *)
DEFINE_DLLAPI_ARG(3, CUresult, cuDeviceGetPCIBusId, char *, int, CUdevice)
DEFINE_DLLAPI_ARG(2, CUresult, cuIpcGetEventHandle, CUipcEventHandle *, CUevent)
DEFINE_DLLAPI_ARG(2, CUresult, cuIpcOpenEventHandle, CUevent *, CUipcEventHandle)
DEFINE_DLLAPI_ARG(2, CUresult, cuIpcGetMemHandle, CUipcMemHandle *, CUdeviceptr)
DEFINE_DLLAPI_ARG(3, CUresult, cuIpcOpenMemHandle, CUdeviceptr *, CUipcMemHandle, unsigned int)
DEFINE_DLLAPI_ARG(1, CUresult, cuIpcCloseMemHandle, CUdeviceptr)
DEFINE_DLLAPI_ARG(3, CUresult, cuMemHostRegister, void *, int, unsigned int)
DEFINE_DLLAPI_ARG(1, CUresult, cuMemHostUnregister, void *)
DEFINE_DLLAPI_ARG(3, CUresult, cuMemcpy, CUdeviceptr, CUdeviceptr, int)
DEFINE_DLLAPI_ARG(5, CUresult, cuMemcpyPeer, CUdeviceptr, CUcontext, CUdeviceptr, CUcontext, int)
DEFINE_DLLAPI_ARG(3, CUresult, cuMemcpyHtoD, CUdeviceptr, const void *, int)
DEFINE_DLLAPI_ARG(3, CUresult, cuMemcpyHtoD_v2, CUdeviceptr, const void *, int)
DEFINE_DLLAPI_ARG(3, CUresult, cuMemcpyDtoH, void *, CUdeviceptr, int)
DEFINE_DLLAPI_ARG(3, CUresult, cuMemcpyDtoH_v2, void *, CUdeviceptr, int)
DEFINE_DLLAPI_ARG(3, CUresult, cuMemcpyDtoD, CUdeviceptr, CUdeviceptr, int)
DEFINE_DLLAPI_ARG(3, CUresult, cuMemcpyDtoD_v2, CUdeviceptr, CUdeviceptr, int)
DEFINE_DLLAPI_ARG(4, CUresult, cuMemcpyDtoA, CUarray, int, CUdeviceptr, int)
DEFINE_DLLAPI_ARG(4, CUresult, cuMemcpyDtoA_v2, CUarray, int, CUdeviceptr, int)
DEFINE_DLLAPI_ARG(4, CUresult, cuMemcpyAtoD, CUdeviceptr, CUarray, int, int)
DEFINE_DLLAPI_ARG(4, CUresult, cuMemcpyAtoD_v2, CUdeviceptr, CUarray, int, int)
DEFINE_DLLAPI_ARG(4, CUresult, cuMemcpyHtoA, CUarray, int, const void *, int)
DEFINE_DLLAPI_ARG(4, CUresult, cuMemcpyHtoA_v2, CUarray, int, const void *, int)
DEFINE_DLLAPI_ARG(4, CUresult, cuMemcpyAtoH, void *, CUarray, int, int)
DEFINE_DLLAPI_ARG(4, CUresult, cuMemcpyAtoH_v2, void *, CUarray, int, int)
DEFINE_DLLAPI_ARG(5, CUresult, cuMemcpyAtoA, CUarray, int, CUarray, int, int)
DEFINE_DLLAPI_ARG(5, CUresult, cuMemcpyAtoA_v2, CUarray, int, CUarray, int, int)
DEFINE_DLLAPI_ARG(1, CUresult, cuMemcpy2D, const CUDA_MEMCPY2D *)
DEFINE_DLLAPI_ARG(1, CUresult, cuMemcpy2D_v2, const CUDA_MEMCPY2D *)
DEFINE_DLLAPI_ARG(1, CUresult, cuMemcpy2DUnaligned, const CUDA_MEMCPY2D *)
DEFINE_DLLAPI_ARG(1, CUresult, cuMemcpy2DUnaligned_v2, const CUDA_MEMCPY2D *)
DEFINE_DLLAPI_ARG(1, CUresult, cuMemcpy3D, const CUDA_MEMCPY3D *)
DEFINE_DLLAPI_ARG(1, CUresult, cuMemcpy3D_v2, const CUDA_MEMCPY3D *)
DEFINE_DLLAPI_ARG(1, CUresult, cuMemcpy3DPeer, const CUDA_MEMCPY3D_PEER *)
DEFINE_DLLAPI_ARG(4, CUresult, cuMemcpyAsync, CUdeviceptr, CUdeviceptr, int, CUstream)
DEFINE_DLLAPI_ARG(6, CUresult, cuMemcpyPeerAsync, CUdeviceptr, CUcontext, CUdeviceptr, CUcontext, int, CUstream)
DEFINE_DLLAPI_ARG(4, CUresult, cuMemcpyHtoDAsync, CUdeviceptr, const void *, int, CUstream)
DEFINE_DLLAPI_ARG(4, CUresult, cuMemcpyHtoDAsync_v2, CUdeviceptr, const void *, int, CUstream)
DEFINE_DLLAPI_ARG(4, CUresult, cuMemcpyDtoHAsync, void *, CUdeviceptr, size_t, CUstream)
DEFINE_DLLAPI_ARG(4, CUresult, cuMemcpyDtoHAsync_v2, void *, CUdeviceptr, size_t, CUstream)
DEFINE_DLLAPI_ARG(4, CUresult, cuMemcpyDtoDAsync, CUdeviceptr, CUdeviceptr, int, CUstream)
DEFINE_DLLAPI_ARG(4, CUresult, cuMemcpyDtoDAsync_v2, CUdeviceptr, CUdeviceptr, int, CUstream)
DEFINE_DLLAPI_ARG(5, CUresult, cuMemcpyHtoAAsync, CUarray, int, const void *, int, CUstream)
DEFINE_DLLAPI_ARG(5, CUresult, cuMemcpyHtoAAsync_v2, CUarray, int, const void *, int, CUstream)
DEFINE_DLLAPI_ARG(5, CUresult, cuMemcpyAtoHAsync, void *, CUarray, int, int, CUstream)
DEFINE_DLLAPI_ARG(5, CUresult, cuMemcpyAtoHAsync_v2, void *, CUarray, int, int, CUstream)
DEFINE_DLLAPI_ARG(2, CUresult, cuMemcpy2DAsync, const CUDA_MEMCPY2D *, CUstream)
DEFINE_DLLAPI_ARG(2, CUresult, cuMemcpy2DAsync_v2, const CUDA_MEMCPY2D *, CUstream)
DEFINE_DLLAPI_ARG(2, CUresult, cuMemcpy3DAsync, const CUDA_MEMCPY3D *, CUstream)
DEFINE_DLLAPI_ARG(2, CUresult, cuMemcpy3DAsync_v2, const CUDA_MEMCPY3D *, CUstream)
DEFINE_DLLAPI_ARG(2, CUresult, cuMemcpy3DPeerAsync, const CUDA_MEMCPY3D_PEER *, CUstream)
DEFINE_DLLAPI_ARG(3, CUresult, cuMemsetD8, CUdeviceptr, unsigned char, int)
DEFINE_DLLAPI_ARG(3, CUresult, cuMemsetD8_v2, CUdeviceptr, unsigned char, int)
DEFINE_DLLAPI_ARG(3, CUresult, cuMemsetD16, CUdeviceptr, unsigned short, int)
DEFINE_DLLAPI_ARG(3, CUresult, cuMemsetD16_v2, CUdeviceptr, unsigned short, int)
DEFINE_DLLAPI_ARG(3, CUresult, cuMemsetD32, CUdeviceptr, unsigned int, int)
DEFINE_DLLAPI_ARG(3, CUresult, cuMemsetD32_v2, CUdeviceptr, unsigned int, int)
DEFINE_DLLAPI_ARG(5, CUresult, cuMemsetD2D8, CUdeviceptr, int, unsigned char, int, int)
DEFINE_DLLAPI_ARG(5, CUresult, cuMemsetD2D8_v2, CUdeviceptr, int, unsigned char, int, int)
DEFINE_DLLAPI_ARG(5, CUresult, cuMemsetD2D16, CUdeviceptr, int, unsigned short, int, int)
DEFINE_DLLAPI_ARG(5, CUresult, cuMemsetD2D16_v2, CUdeviceptr, int, unsigned short, int, int)
DEFINE_DLLAPI_ARG(5, CUresult, cuMemsetD2D32, CUdeviceptr, int, unsigned int, int, int)
DEFINE_DLLAPI_ARG(5, CUresult, cuMemsetD2D32_v2, CUdeviceptr, int, unsigned int, int, int)
DEFINE_DLLAPI_ARG(4, CUresult, cuMemsetD8Async, CUdeviceptr, unsigned char, int, CUstream)
DEFINE_DLLAPI_ARG(4, CUresult, cuMemsetD16Async, CUdeviceptr, unsigned short, int, CUstream)
DEFINE_DLLAPI_ARG(4, CUresult, cuMemsetD32Async, CUdeviceptr, unsigned int, int, CUstream)
DEFINE_DLLAPI_ARG(6, CUresult, cuMemsetD2D8Async, CUdeviceptr, int, unsigned char, int, int, CUstream)
DEFINE_DLLAPI_ARG(6, CUresult, cuMemsetD2D16Async, CUdeviceptr, int, unsigned short, int, int, CUstream)
DEFINE_DLLAPI_ARG(6, CUresult, cuMemsetD2D32Async, CUdeviceptr, int, unsigned int, int, int, CUstream)
DEFINE_DLLAPI_ARG(2, CUresult, cuArrayCreate, CUarray *, const CUDA_ARRAY_DESCRIPTOR *)
DEFINE_DLLAPI_ARG(2, CUresult, cuArrayCreate_v2, CUarray *, const CUDA_ARRAY_DESCRIPTOR *)
DEFINE_DLLAPI_ARG(2, CUresult, cuArrayGetDescriptor, CUDA_ARRAY_DESCRIPTOR *, CUarray)
DEFINE_DLLAPI_ARG(2, CUresult, cuArrayGetDescriptor_v2, CUDA_ARRAY_DESCRIPTOR *, CUarray)
DEFINE_DLLAPI_ARG(1, CUresult, cuArrayDestroy, CUarray)
DEFINE_DLLAPI_ARG(2, CUresult, cuArray3DCreate, CUarray *, const CUDA_ARRAY3D_DESCRIPTOR *)
DEFINE_DLLAPI_ARG(2, CUresult, cuArray3DCreate_v2, CUarray *, const CUDA_ARRAY3D_DESCRIPTOR *)
DEFINE_DLLAPI_ARG(2, CUresult, cuArray3DGetDescriptor, CUDA_ARRAY3D_DESCRIPTOR *, CUarray)
DEFINE_DLLAPI_ARG(2, CUresult, cuArray3DGetDescriptor_v2, CUDA_ARRAY3D_DESCRIPTOR *, CUarray)
DEFINE_DLLAPI_ARG(3, CUresult, cuPointerGetAttribute, void *, CUpointer_attribute, CUdeviceptr)
DEFINE_DLLAPI_ARG(2, CUresult, cuStreamCreate, CUstream *, unsigned int)
DEFINE_DLLAPI_ARG(3, CUresult, cuStreamWaitEvent, CUstream, CUevent, unsigned int)
DEFINE_DLLAPI_ARG(1, CUresult, cuStreamQuery, CUstream)
DEFINE_DLLAPI_ARG(1, CUresult, cuStreamSynchronize, CUstream)
DEFINE_DLLAPI_ARG(1, CUresult, cuStreamDestroy, CUstream)
DEFINE_DLLAPI_ARG(1, CUresult, cuStreamDestroy_v2, CUstream)
DEFINE_DLLAPI_ARG(2, CUresult, cuEventCreate, CUevent *, unsigned int)
DEFINE_DLLAPI_ARG(2, CUresult, cuEventRecord, CUevent, CUstream)
DEFINE_DLLAPI_ARG(1, CUresult, cuEventQuery, CUevent)
DEFINE_DLLAPI_ARG(1, CUresult, cuEventSynchronize, CUevent)
DEFINE_DLLAPI_ARG(1, CUresult, cuEventDestroy, CUevent)
DEFINE_DLLAPI_ARG(1, CUresult, cuEventDestroy_v2, CUevent)
DEFINE_DLLAPI_ARG(3, CUresult, cuEventElapsedTime, float *, CUevent, CUevent)
DEFINE_DLLAPI_ARG(3, CUresult, cuFuncGetAttribute, int *, CUfunction_attribute, CUfunction)
DEFINE_DLLAPI_ARG(2, CUresult, cuFuncSetCacheConfig, CUfunction, CUfunc_cache)
DEFINE_DLLAPI_ARG(2, CUresult, cuFuncSetSharedMemConfig, CUfunction, CUsharedconfig)
DEFINE_DLLAPI_ARG(11, CUresult, cuLaunchKernel, CUfunction, unsigned int, unsigned int, unsigned int, unsigned int, unsigned int, unsigned int, unsigned int, CUstream, void **, void **)
DEFINE_DLLAPI_ARG(4, CUresult, cuFuncSetBlockShape, CUfunction, int, int, int)
DEFINE_DLLAPI_ARG(2, CUresult, cuFuncSetSharedSize, CUfunction, unsigned int)
DEFINE_DLLAPI_ARG(2, CUresult, cuParamSetSize, CUfunction, unsigned int)
DEFINE_DLLAPI_ARG(3, CUresult, cuParamSeti, CUfunction, int, unsigned int)
DEFINE_DLLAPI_ARG(3, CUresult, cuParamSetf, CUfunction, int, float)
DEFINE_DLLAPI_ARG(4, CUresult, cuParamSetv, CUfunction, int, void *, unsigned int)
DEFINE_DLLAPI_ARG(1, CUresult, cuLaunch, CUfunction)
DEFINE_DLLAPI_ARG(3, CUresult, cuLaunchGrid, CUfunction, int, int)
DEFINE_DLLAPI_ARG(4, CUresult, cuLaunchGridAsync, CUfunction, int, int, CUstream)
DEFINE_DLLAPI_ARG(3, CUresult, cuParamSetTexRef, CUfunction, int, CUtexref)
DEFINE_DLLAPI_ARG(3, CUresult, cuTexRefSetArray, CUtexref, CUarray, unsigned int)
DEFINE_DLLAPI_ARG(4, CUresult, cuTexRefSetAddress, int *, CUtexref, CUdeviceptr, int)
DEFINE_DLLAPI_ARG(4, CUresult, cuTexRefSetAddress_v2, int *, CUtexref, CUdeviceptr, int)
DEFINE_DLLAPI_ARG(4, CUresult, cuTexRefSetAddress2D, CUtexref, const CUDA_ARRAY_DESCRIPTOR *, CUdeviceptr, int)
DEFINE_DLLAPI_ARG(4, CUresult, cuTexRefSetAddress2D_v3, CUtexref, const CUDA_ARRAY_DESCRIPTOR *, CUdeviceptr, int)
DEFINE_DLLAPI_ARG(3, CUresult, cuTexRefSetFormat, CUtexref, CUarray_format, int)
DEFINE_DLLAPI_ARG(3, CUresult, cuTexRefSetAddressMode, CUtexref, int, CUaddress_mode)
DEFINE_DLLAPI_ARG(2, CUresult, cuTexRefSetFilterMode, CUtexref, CUfilter_mode)
DEFINE_DLLAPI_ARG(2, CUresult, cuTexRefSetFlags, CUtexref, unsigned int)
DEFINE_DLLAPI_ARG(2, CUresult, cuTexRefGetAddress, CUdeviceptr *, CUtexref)
DEFINE_DLLAPI_ARG(2, CUresult, cuTexRefGetAddress_v2, CUdeviceptr *, CUtexref)
DEFINE_DLLAPI_ARG(2, CUresult, cuTexRefGetArray, CUarray *, CUtexref)
DEFINE_DLLAPI_ARG(3, CUresult, cuTexRefGetAddressMode, CUaddress_mode *, CUtexref, int)
DEFINE_DLLAPI_ARG(2, CUresult, cuTexRefGetFilterMode, CUfilter_mode *, CUtexref)
DEFINE_DLLAPI_ARG(3, CUresult, cuTexRefGetFormat, CUarray_format *, int *, CUtexref)
DEFINE_DLLAPI_ARG(2, CUresult, cuTexRefGetFlags, unsigned int *, CUtexref)
DEFINE_DLLAPI_ARG(1, CUresult, cuTexRefCreate, CUtexref *)
DEFINE_DLLAPI_ARG(1, CUresult, cuTexRefDestroy, CUtexref)
DEFINE_DLLAPI_ARG(3, CUresult, cuSurfRefSetArray, CUsurfref, CUarray, unsigned int)
DEFINE_DLLAPI_ARG(2, CUresult, cuSurfRefGetArray, CUarray *, CUsurfref)
DEFINE_DLLAPI_ARG(3, CUresult, cuDeviceCanAccessPeer, int *, CUdevice, CUdevice)
DEFINE_DLLAPI_ARG(2, CUresult, cuCtxEnablePeerAccess, CUcontext, unsigned int)
DEFINE_DLLAPI_ARG(1, CUresult, cuCtxDisablePeerAccess, CUcontext)
DEFINE_DLLAPI_ARG(1, CUresult, cuGraphicsUnregisterResource, CUgraphicsResource)
DEFINE_DLLAPI_ARG(4, CUresult, cuGraphicsSubResourceGetMappedArray, CUarray *, CUgraphicsResource, unsigned int, unsigned int)
DEFINE_DLLAPI_ARG(3, CUresult, cuGraphicsResourceGetMappedPointer, CUdeviceptr *, int *, CUgraphicsResource)
DEFINE_DLLAPI_ARG(3, CUresult, cuGraphicsResourceGetMappedPointer_v2, CUdeviceptr *, int *, CUgraphicsResource)
DEFINE_DLLAPI_ARG(2, CUresult, cuGraphicsResourceSetMapFlags, CUgraphicsResource, unsigned int)
DEFINE_DLLAPI_ARG(3, CUresult, cuGraphicsMapResources, unsigned int, CUgraphicsResource *, CUstream)
DEFINE_DLLAPI_ARG(3, CUresult, cuGraphicsUnmapResources, unsigned int, CUgraphicsResource *, CUstream)
DEFINE_DLLAPI_ARG(2, CUresult, cuGetExportTable, const void **, const CUuuid *)

#if defined(__x86_64) || defined(AMD64) || defined(_M_AMD64)
DEFINE_DLLAPI_ARG(2, CUresult, cuMemAllocHost, void **, unsigned int)
DEFINE_DLLAPI_ARG(2, CUresult, cuMemAllocHost_v2, void **, unsigned int)
DEFINE_DLLAPI_ARG(4, CUresult, cuMemcpyDtoHAsync, void *, CUdeviceptr, unsigned int, CUstream)
DEFINE_DLLAPI_ARG(4, CUresult, cuMemcpyDtoHAsync_v2, void *, CUdeviceptr, unsigned int, CUstream)
#endif

//} //namespace cuda
//} //namespace dllapi
